services:
  - type: web
    name: tiktok-youtube-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python app.py
    plan: free
